RMS/RMS/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ResumeMangementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from ResumeMangementSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('process.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

process/urls.py
from django.urls import path
from process import views


urlpatterns = [
    path('', views.showIndex, name='main_page'),
    path('registration/', views.registration, name='registration'),
    path('user_registration/', views.registration, name='user_registration'),
    path('validation_otp/',  views.validate_otp, name='validate_otp'),
    #otp page
    path('user_otp/', views.userOTP, name='user-otp'),
    # conformation
    path('conformation/', views.conformation, name='conformation'),

    #login
    path('login/', views.login, name='login'),
    #for login check
    path('login_check/', views.login_check, name='login_check'),
    path('view_profile/', views.view_profile, name='view_profile'),
    path('logout/',views.logout,name='logout'),

]

process/models.py
from django.db import models

# Create your models here.

class RegistrationModel(models.Model):
    rno = models.AutoField(primary_key = True)
    name =  models.CharField(max_length=100)
    contact = models.IntegerField(unique=True)
    email =  models.EmailField(unique=True)
    password = models.CharField(max_length=30)
    otp = models.IntegerField()
    doj =  models.DateField(auto_now_add=True)
    status = models.CharField(max_length=100,default="pending")

class IndustriesModel(models.Model):
    ino = models.AutoField(primary_key = True)
    type = models.CharField(max_length=100)

class ProfileModel(models.Model):
    pno = models.AutoField(primary_key = True)
    person = models.OneToOneField(RegistrationModel, on_delete=models.CASCADE)
    education = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="user_images/")
    resume =  models.FileField(upload_to="user_images/")
    itype = models.ForeignKey(IndustriesModel,on_delete=models.CASCADE)

process/forms.py
from django import forms
from process.models import *
import random
# from process.utils import sendTextMessage
from django.conf import settings 
from django.core.mail import send_mail

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    def clean_otp(self):
        email =  self.cleaned_data['email']
        # otp = self.cleaned_data['otp']
        otp = random.randint(100000,999999)
        touser = email
        sub = 'OTP'
        body = 'Welcome to RMS and Your OTP is' + str(otp)
        efrom = settings.EMAIL_HOST_USER
        reclist = [touser]
        send_mail(sub, body, efrom,reclist)
        
       # message = 'Welcome to RMS and Your OTP is' + str(otp)
        #sendTextMessage(message, cno)
        return otp
    
    class Meta:
        model = RegistrationModel
        exclude = ('status',)

process/views.py
from django.shortcuts import render, redirect
from process.forms import RegistrationForm
from process.models import RegistrationModel
from django.contrib.messages import success

# Create your views here.

def showIndex(request):
    return render(request, 'process_templates/main.html')

def registration(request):
    rf = RegistrationForm(request.POST)
    if request.method == "POST":
        if rf.is_valid():
            rf.save()
            return redirect('user-otp')

        else:
            return render(request, 'process_templates/registration.html', {'form':rf})
    else:
        return render(request, 'process_templates/registration.html', {'form': rf})

def userOTP(request):
    return render(request,"process_templates/otp.html")

def validate_otp(request):
    try:
        result = RegistrationModel.objects.get(contact = request.POST.get("t1"),otp = request.POST.get("t2"))
        if result.status == "pending":
            result.status = "approved"
            result.save()
            success(request, "Thanks for Registration")
            return redirect('conformation')
        elif result.status == "approved":
            success(request, "Your Registration is Already Approved")
            return redirect('conformation')
        #elif result.status == "blocked":

    except RegistrationModel.DoesNotExist:
        message =  "Sorry Invalid Details Please Try Again"
        return render(request, 'process_templates/otp.html', {'message':message})

def conformation(request):
    return render(request, 'process_templates/conformation.html')

def login(request):
    return render(request, 'process_templates/login.html')

def login_check(request):
    try:
        result = RegistrationModel.objects.get(email = request.POST.get('u1'), password = request.POST.get('u2'))
        if result.status == "pending":
            return render(request, "process_templates/login.html", {"error": "Sorry Your Registration is not Approved"})
        if result.status == "closed":
            return render(request, "process_templates/login.html", {"error": "Sorry Your Account is Closed"})
        request.session["contact"] = result.contact
        request.session["name"] = result.name
        return redirect('view_profile')
    except RegistrationModel.DoesNotExist:
        return render(request, 'process_templates/login.html', {'error':'Invalid User'})

def view_profile(request):
    return render(request, 'process_templates/view_profile.html')

def logout(request):
     del request.session["contact"]
     del request.session["name"]
     return redirect('main_page')

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Resume Management System</title>
    <style>
      {% comment %} .menu{
        border-radius:10px;
        border-color :black;
        border-width:2px;
        border-style:solid;
        margin-right:10px;
        background-color:green;
      } {% endcomment %}
    </style>
  </head>
  <body>
    <table class="table-responsive-md table-borderless" align = "center" width="100%">
    <tr>
      <th style="background-color: #330066; text-align : center; padding:10px">
      <img src="{% static 'images/logo.png' %}" width="100" height="100"></th>
      <th style="background-color: #330066; font-family: 'Agency FB';font-size: 50px;color: white;text-align: center;padding: 10px">Resume Management System</th>
    </tr>
  
    <tr>
      <th colspan="2">
      
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <div class="menu">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main_page' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      </div>

      

      <div class="menu">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'registration' %}">Registration <span class="sr-only">(current)</span></a>
      </li>
      </div>

      <div class="menu">
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile <span class="sr-only">(current)</span></a>
        </a>
        <div class="dropdown-menu menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'view_profile' %}">View Profile</a>
          <a class="dropdown-item" href="#">Update Profile</a>
          <a class="dropdown-item" href="#">Delete Profile</a>
        </div>
      </li>
        </div>

        <div class="menu">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
      </li>
      </div>
      <div class="menu">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
      </li>
      </div>

      <div class="menu">
      <li class="nav-item active">
        <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
      </li>
      </div>

      
    </ul>
  </div>
</nav>

      </th>
      
    </tr>
  
    <tr>
      <th colspan="2" style ="text-align:center">
        {% block content %}

        {% endblock  %}     
      </th>
  
    </tr>
  
    <tr>
      <th colspan="2" style="background-color: #330066; text-align:center; color:white;">Copyright &copy iftekhar</th>
     
    </tr>
    </table>

   
   
    <!-- Optional JavaScript; choose one of the two! -->
     <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/process_templates/conformation.html
{% extends 'index.html' %}
{% block content %}
    {% load static %}
    {% for x in messages %}
    <h1> {{x}} </h1>
    
    {% endfor %}

    <a href ={%url 'login' %}> login From Hree</a>
{% endblock  %}

templates/process_templates/login.html
{% extends 'index.html' %}


{% block content %}

    {% load static %}

   {% if request.session.contact %}
   
   
    {% else %}
   <div class="container">
    <form action="{% url 'login_check'%}" method="post">
    {% csrf_token %}
    <h1>Welcome Login page</h1>
    <input type="email" placeholder="Email" required name="u1"><br>
    <input type="password" placeholder="Password" required name="u2"><br>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
    </div>
    </form>
    
    {% if error %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Error!..... </strong> {{ error }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}

    {% endif %}
    
   

{% endblock %}

templates/process_templates/main.html
{% extends 'index.html' %}

{% block content %}
    {% load static %}
    <table class="table table-borderless" align="center">
        <tr>
            <th>Resumes are a great way by which you can identify quality talent but they have a major problem: recruiters have a hard time managing and organizing these resumes to pick the relevant ones.
<br><br>
Often called resume management software, but known by many other names - resume sorting software, resume filtering software, resume database management software - the concept is the same: they’re software used to source, collect, parse, organize and store the resumes in a central database. <br><br>Perhaps, resume management system predominantly focuses on cutting down manual work involved in organizing the plethora of resumes that come in. </th>
            <th>
                <img src="{% static 'images/image1.png' %}">
            </th>
        </tr>
    </table>
{% endblock %}

templates/process_templates/otp.html
{% extends 'index.html' %}

{% block content %}

    {% load static %}

    <form action="{%url 'validate_otp' %}" method="post">
    {% csrf_token %}
    <table align ="center" border="0">
    <tr>
        <th colspan="2">OTP Validation Page</th>
    </tr>
    <tr>
        <th>Contact No</th>
        <th><input type="number" required name="t1"></th>
    </tr>
    <tr>
    <th>OTP</th>
    <th><input type="number" required name="t2"></th>
    </tr>
    <tr>
    <th colspan="2"><button type="submit">Submit</button>
    </th>
    </table>
    </form>

    {% if message %}
    <h1 style="
        font-size:35px;
        font-family:'Agency FB';
        color:white;
        text-align: center;
        background-color: red "> 
        {{message}}</h1>
    
    
    {% endif %}

{% endblock %}

templates/process_templates/registration.html
{% extends 'index.html' %}

{% block content %}

<form method="post" action="{% url 'user_registration' %}">
{% csrf_token %}

<table align="center" border="0">
<tr>
<th colspan="2"><h1>Registration Page</h1></th>
</tr>
<tr>
<th>{{form.name.label}}</th>
<th>{{form.name}}</th>
</tr>
<tr>
<th>{{form.contact.label}}</th>
<th>{{form.contact}}</th>
</tr>
<tr>
<th>{{form.email.label}}</th>
<th>{{form.email}}</th>
</tr>
<tr>
<th>{{form.password.label}}</th>
<th>{{form.password}}</th>
</tr>
<tr>
    
    <th><input type="hidden" name="otp" required="" id="id_otp" value="0"></th>
</tr>
<tr><th colspan="2"><button type="submit" class="btn btn-primary">Save</button></th></tr>
    

</table>

</form>
{% endblock  %}

templates/process_templates/view_profile.html
{% extends 'index.html' %}
{% block content %}

    {% load static %}

   {% if request.session.contact %}
   <h1>Welocome to Profile Page</h1>
   <h2>Mr/Miss: {{request.session.name}}</h2>
   {% else %}
   <h1>Please Do login first</h1>
   <h4>Without Login You cannot access this page</h4>
  
   {% endif %}

{% endblock %}